### ISSUE TITLE
search doesnt work for special chars

### ISSUE THREAD

**Issue by pilec** [DwarfSearch/DwarfSearch#22]
try search: cvaláme and cváláme - compare results.

**Comment by pilec** [comment]
Pořad to na vyhledani "cvalame" nenajde - cvalame na neosedlanem koni po zadelane draze :-(

**Comment by legendik** [comment]
Grrrr. Ono totiž to `Cváláme` bylo s velkým `C`. FIxed :-)

**Comment by pilec** [comment]
:+1:
